### ISSUE TITLE
Date conflicts with #PerfMatters Conference

### ISSUE THREAD

**Issue by estelle** [HTTPWorkshop/workshop2019#2]
Any chance you can push it out a week? Not sure if this was just announced or has been a long time in the planning. If not, there is an overlap: some people would love to attend both.

Here's to hoping.

https://perfmattersconf.com is April 1-4 in california.

**Comment by reschke** [comment]
The goal was to be back-to-back with https://www.ietf.org/how/meetings/104/ (which is also in Europe).

**Comment by estelle** [comment]
Understood. Thanks.
